/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    'Acquire chess skills': '获得国际象棋技能',
    'Build a Lab': '建立一个实验室',
    'CLICK': '点击',
    'Click here to close': '点击这里关闭',
    'Click upgrades': '点击升级',
    'Clicks': '点击',
    'Click power': '点击力量',
    'Click Power': '点击力量',
    'laptop': '笔记本电脑',
    'Build an University': '建立一个大学',
    'Change theme': '更换主题',
    'Enable explosions effects': '启用爆炸效果',
    'Disable explosions effects': '禁用爆炸效果',
    'Disable particles effects': '禁用粒子效果',
    'Enable particle effects': '启用粒子效果',
    'Reset': '重置',
    'Reward': '奖励',
    'settings': '设置',
    'Setts': '设置',
    'Sound': '声音',
    'Teach Power': '教导力量',
    'Unlock Apprentices': '解锁学徒',
    'upgrade': '升级',
    'Upgrades': '升级',
    'Play Fibonacci Cliker': '开始游戏',
    'Background color': '背景色',
    'Welcome to Fibonacci idle.': '欢迎来到斐波那契放置。',
    'Next reset: +': '下次重置: +',
    'Meet Bill Gates': '认识比尔盖茨',
    'Meet Dumbledore': '认识邓布利多',
    'Master Quantum Physics': '量子物理学硕士',
    'Master Medicine': '医学硕士',
    'Master Mechanics': '机械学硕士',
    'Master Maths': '数学硕士',
    'Master Computer Science': '计算机科学硕士',
    'To start playing click on the canvas on my left.': '要开始游戏，请单击我左侧的画布。',
    'To stay\ntuned on my games': '保持\n关注我的游戏',
    'to unlock apprentices upgrades': '解锁学徒升级',
    'When you hit the bug you won 50x you atual power': '当您击中Bug时，您将获得 50 倍的实际力量',
    'You need to build a school': '你需要建一所学校',
    'You need to reset to get research points': '你需要重置才能获得研究点数',
    'You will lose all the progress and start over with\na bigger difficulty': '您将失去所有进度并以更大的难度重新开始',
    'Φ is the representation of knowledge. You can use it to develop': 'Φ 是知识的表示。 你可以用它来开发',
    'Appts power': '自动点击力量',
    'Build a Biblio': '建立一个书目',
    'Build a school': '建一所学校',
    'Check settings to know how much you\nhave.': '检查设置以了解您\有多少。',
    'Click power is the qtd of Φ you create for every click on the canvas': '点击功率是您为画布上的每次点击创建的 Φ 的 qtd',
    'Fibonacci Level': '斐波那契等级',
    'Go to': '前往',
    'Hire more teachers': '聘请更多教师',
    'Is the amount of times the bonus multiplies the number of blocks shoot': '奖励的数量是否与射击的方块数量相乘',
    'Acquire poker skills': '掌握扑克技能',
    'Advertises your School': '为您的学校做广告',
    'Apprentices': '学徒',
    'Apprentices power it\'s based on teach power, the number of apprentices you got and your atual Φ': '学徒力量它基于教学力量，您获得的学徒数量和您的实际Φ',
    'Apprentices upgrades': '学徒升级',
    'It is the number of apprentices you are teaching': '这是你教的学徒人数',
    'It is the power of each block you shoot each click': '这是你每次点击每个块的力量',
    'It is the probability to appear a bonus item in the bottom of the left\ncanvas': '左下角出现奖励物品的概率\n画布',
    'It is the teach power you got.': '这是你得到的教导力量。',
    'person': '人',
    'Randomize square colors': '随机化方块颜色',
    'Requires': '需要',
    'Research': '研究',
    'research points': '研究点',
    'Research Points': '研究点',
    'Research points are created based on your total Φ ever.': '研究点是根据您的总 Φ 创建的。',
    'Reset your researchs and give your research points back': '重置你的研究并返还你的研究点数',
    'CLICK HERE': '点这里',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //树游戏
    'Loading...': '加载中...',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Finish Level ": "完成等级 ",
    "Fibonacci Level ": "斐波那契等级 ",
    "Reward: ": "奖励: ",
    "Teacher power ": "教师力量 ",
    "Theme color": "主题颜色",
    "Time Played": "游戏时长",
    "I chose some of my apprentices to help you while you were out. They helped you with ": "我选择了我的一些徒弟在你外出时帮助你。 他们帮助你得到了 ",
    "Research Points: ": "研究点：",
    "Bonus chance": "奖励几率",
    "Apprentices\nnumber ": "学徒\n人数",
    "Apprentices number ": "学徒人数",
    "Bonus multiplier": "奖励倍数",
    "Power ": "力量 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) Apprentice$/, '$1 学徒'],
    [/^Level  ([\d\.]+)$/, '等级 $1'],
    [/^level ([\d\.]+)$/, '等级 $1'],
    [/^Level ([\d\.]+): ([\d\.]+)$/, '等级 $1：$2'],
    [/^level ([\d\.]+): ([\d\.]+)$/, '等级 $1：$2'],
    [/^Welcome back you stayed (\d+) seconds.$/, '欢迎回来，您离开了 $1 秒。'],
    [/^Welcome back you stayed (\d+) minutes and (\d+) seconds.$/, '欢迎回来，您离开了 $1 分 $2 秒。'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);